### ISSUE TITLE
Editing app design

### ISSUE THREAD

**Issue by l-goede** [l-goede/sagit#1]
#### Description

Edit app design due to review

#### Tasks
Editing following parts in design 

- [x] Editing Icons thickness
- [x] Editing Save button
- [x] Editing color choice
- [x] Adding placeholder
