### ISSUE TITLE
6- building page "Benachrichtungen"

### ISSUE THREAD

**Issue by l-goede** [l-goede/sagit#10]
#### Description

When a product (saved on watchlist) has reached the set price, the user receives a notification. The product is shifted to the page "Benachrichtigungen"

#### Screenshots
![image](https://user-images.githubusercontent.com/82370303/121336083-78a03f80-c91b-11eb-83cc-c067bc0c7853.png)

#### Tasks

- [ ] Update the current price (from API)
- [ ] Shifting component product tile to page "Benachrichtigungen"
- [ ] integrate logo
- [ ] integrate footer
- [ ] Send notification (symbol on notification bell in footer)

### Challenge
- How to shift the product to page "Benachrichtungen" with updated price
- How to notify the user (user has to agree for sending notifications)
