### ISSUE TITLE
Build API.ts

### ISSUE THREAD

**Issue by l-goede** [l-goede/sagit#12]
#### Description

Create all necessary functions to get the requested data from API
#### Screenshots Bsp (specific API)

 let url = `${BASE_URL}${path}?`;
  if (query) {
    url += `${query}&`;
  }
  url += `api_key=${THE_MOVIE_DB_KEY}`;

  const response = await fetch(url);
  if (!response.ok) {
    const errorResult: ErrorResult = await response.json();
    throw {
      message: errorResult.status_message,
      theMovieDBCode: errorResult.status_code,
      status: response.status,
    };
  }
  const result: T = await response.json();
  return result;
}
 
Pull request:
lmachens/photoplay@cb547e8#diff-15c7576c5aab265c9a6f2a02b1e0061e6bc9bb8474be29c3f529f2ba8d6ad519
#### Tasks

- [x] Create BASE_URL
- [x] Create fetch function
- [ ]Create specific functions for API search

Challenge:
I won't have an API to fetch so I need to adjust the code for getting data!
