### ISSUE TITLE
Connect to mongodb and save credentials in database

### ISSUE THREAD

**Issue by l-goede** [l-goede/sagit#22]
#### Description
Credentials should be saved in db

#### Tasks

- [x] Get connection to mongodb
- [x] Write save credential function
- [x] Write function for saving in mongodb
- [x] Test if its working
