### ISSUE TITLE
Get data from mongoDB and showing on watchlist page

### ISSUE THREAD

**Issue by l-goede** [l-goede/sagit#35]
#### Description

After saving a product, this product should be saved on the page watchlist, so the user can keep track of the price of his target product.

#### Tasks

- [x] Need to build get route for getting data from mongoDB
- [x] Making get request in watchlist page
- [ ] Design how to show the watchlist items
