### ISSUE TITLE
4- building page "Wunschpreiseingabe"

### ISSUE THREAD

**Issue by l-goede** [l-goede/sagit#8]
#### Description

As user you want to set a price for a product you are willing to pay
On this page you can set the price and save
I choose building a modal which pops up when the clicks on a product element and disappears when clicking on the closing button

#### Screenshots

![image](https://user-images.githubusercontent.com/82370303/121332485-345f7000-c918-11eb-9458-10f2eda96e69.png)

#### Tasks
After clicking a product tile the page before, this product will be shown slightly different (bigger picture, product infos below)

- [x] build component of different product tile
- [x] headline for label
- [x] label (& placeholder)
- [x] save button
- [x] change save button design
