### ISSUE TITLE
5 - building page "Merkliste"

### ISSUE THREAD

**Issue by l-goede** [l-goede/sagit#9]
#### Description

After setting a price, the product and "wish price" is saved on page "Merkliste" to record the products and prices the user have chosen.

#### Screenshots

If![image](https://user-images.githubusercontent.com/82370303/121334256-ca47ca80-c919-11eb-846f-d4c705daf5e8.png)

#### Tasks
building a new component: product tile with included "wish price"

- [x] component product tile expanding with wish price and notification (on)
- [ ] notification bell can set off (after saved on watchlist, the notification bell is on by default)
- [x] integrate logo component
- [x] Integrate footer component
